######################################################################
# Automatically generated by qmake (3.0) Fri Feb 19 15:59:52 2016
######################################################################

TEMPLATE = app
TARGET = Gestionale_liteEx
INCLUDEPATH += . Gestionale_lite/HeaderGrafica Gestionale_lite/HeaderLogica


# Input
HEADERS += Gestionale_lite/HeaderGrafica/activityfunzionalitaintroiti.h \
           Gestionale_lite/HeaderGrafica/activityfunzionalitaspese.h \
           Gestionale_lite/HeaderGrafica/activityfunzionalitavario.h \
           Gestionale_lite/HeaderGrafica/activityoreintroiti.h \
           Gestionale_lite/HeaderGrafica/activityspesadipendente.h \
           Gestionale_lite/HeaderGrafica/activityspesagenerale.h \
           Gestionale_lite/HeaderGrafica/activityspesakm.h \
           Gestionale_lite/HeaderGrafica/infosocieta.h \
           Gestionale_lite/HeaderGrafica/mainactivity.h \
           Gestionale_lite/HeaderGrafica/navbarlaterale.h \
           Gestionale_lite/HeaderGrafica/navbarsuperiorefunzionalita.h \
           Gestionale_lite/HeaderGrafica/navbarsuperioreinfo.h \
           Gestionale_lite/HeaderGrafica/navbarsuperioreintroiti.h \
           Gestionale_lite/HeaderGrafica/navbarsuperioreSpese.h \
           Gestionale_lite/HeaderGrafica/titolosuperiore.h \
           Gestionale_lite/HeaderGrafica/welcome.h \
           Gestionale_lite/HeaderGrafica/widgetintroitilavoratore.h \
           Gestionale_lite/HeaderGrafica/widgetspesadipendente.h \
           Gestionale_lite/HeaderGrafica/widgetspesagenerale.h \
           Gestionale_lite/HeaderGrafica/widgetspesakm.h \
           Gestionale_lite/HeaderLogica/durata.h \
           Gestionale_lite/HeaderLogica/introiti_lavoratore.h \
           Gestionale_lite/HeaderLogica/introiti_lavoratoreore.h \
           Gestionale_lite/HeaderLogica/lista_introiti.h \
           Gestionale_lite/HeaderLogica/lista_spese.h \
           Gestionale_lite/HeaderLogica/societa.h \
           Gestionale_lite/HeaderLogica/spesa.h \
           Gestionale_lite/HeaderLogica/spesa_generale.h \
           Gestionale_lite/HeaderLogica/spesa_km.h \
           Gestionale_lite/HeaderLogica/spese_dipendente.h
SOURCES += Gestionale_lite/main.cpp \
           Gestionale_lite/SurcesGrafica/activityfunzionalitaintroiti.cpp \
           Gestionale_lite/SurcesGrafica/activityfunzionalitaspese.cpp \
           Gestionale_lite/SurcesGrafica/activityfunzionalitavario.cpp \
           Gestionale_lite/SurcesGrafica/activityoreintroiti.cpp \
           Gestionale_lite/SurcesGrafica/activityspesadipendente.cpp \
           Gestionale_lite/SurcesGrafica/activityspesagenerale.cpp \
           Gestionale_lite/SurcesGrafica/activityspesakm.cpp \
           Gestionale_lite/SurcesGrafica/infosocieta.cpp \
           Gestionale_lite/SurcesGrafica/mainactivity.cpp \
           Gestionale_lite/SurcesGrafica/navbarlaterale.cpp \
           Gestionale_lite/SurcesGrafica/navbarsuperiorefunzionalita.cpp \
           Gestionale_lite/SurcesGrafica/navbarsuperioreinfo.cpp \
           Gestionale_lite/SurcesGrafica/navbarsuperioreintroiti.cpp \
           Gestionale_lite/SurcesGrafica/navbarsuperioreSpese.cpp \
           Gestionale_lite/SurcesGrafica/titolosuperiore.cpp \
           Gestionale_lite/SurcesGrafica/welcome.cpp \
           Gestionale_lite/SurcesGrafica/widgetintroitilavoratore.cpp \
           Gestionale_lite/SurcesGrafica/widgetspesadipendente.cpp \
           Gestionale_lite/SurcesGrafica/widgetspesagenerale.cpp \
           Gestionale_lite/SurcesGrafica/widgetspesakm.cpp \
           Gestionale_lite/SurcesLogica/durata.cpp \
           Gestionale_lite/SurcesLogica/introiti_lavoratore.cpp \
           Gestionale_lite/SurcesLogica/introiti_lavoratoreore.cpp \
           Gestionale_lite/SurcesLogica/lista_introiti.cpp \
           Gestionale_lite/SurcesLogica/lista_spese.cpp \
           Gestionale_lite/SurcesLogica/societa.cpp \
           Gestionale_lite/SurcesLogica/spesa.cpp \
           Gestionale_lite/SurcesLogica/spesa_generale.cpp \
           Gestionale_lite/SurcesLogica/spesa_km.cpp \
           Gestionale_lite/SurcesLogica/spese_dipendente.cpp
